import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home({ secret, nextSecret, thirdValue }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>NextJs Environment Variables</h1>
				<h2>.ENV Value: {secret}</h2>
				<h2>.ENV Value of Next Public: {nextSecret}</h2>
				<h2>Third Value: {thirdValue}</h2>
			</main>
		</div>
	);
}

export const getStaticProps = () => {
	return {
		props: {
			secret: process.env.NAME,
			nextSecret: process.env.NEXT_PUBLIC_VALUE,
			thirdValue: process.env.THIRD_VALUE
		}
	};
};
